### ISSUE TITLE
caddy.socket should probably bind to `[::]` instead of `0.0.0.0`

### ISSUE THREAD

**Issue by Job79** [eriksjolund/podman-caddy-socket-activation#17]
Hi! Thanks for the examples, they where a great help to get the caddy beta with socket activation working.

I saw that you didn't test example 3 and 4, so I am creating an issue to let you know that they mostly worked when I tried them. I tested them on 2 different deployments (modified to my own domains and config structure).

The problem I encountered was that http3 didn't work on 1 of the deployments. After some testing I found that http3 worked with curl but not with chromium, firefox or https://http3check.net. After some digging I found the cause: the systemd socket doesn't bind to the ipv6 address and somehow that is preventing http3 from working inside browsers. After modifying the `ListenDatagram=0.0.0.0:443` line to `ListenDatagram=[::]:443` http3 started working inside chromium and firefox. It worked on the other deployment because it doesn't have ipv6 ;)

So I think it might be a good idea to modify the example so they bind to `[::]` by default? It should result in the socket binding to both ipv4 and ipv6, but maybe set `BindIPv6Only=both` to be sure (I didn't need it on coreos, but other distro's could have a different default). 

If you would like my help to test some other things let me know, I would be happy to assist.

**Comment by eriksjolund** [comment]
Thanks, I opened a PR.

> If you would like my help to test some other things let me know, I would be happy to assist.
I have nothing right now that I come to think of. Thanks anyway!
